/**
 * Substring dictionary for merchant strings (after lowercasing). Longer phrases are
 * checked first so "whole foods market" wins over "whole foods".
 * @type {Array<[string, import("./categories.js").CategoryId]>}
 */
const SNIPPETS_RAW = [
  // Travel (long phrases first)
  ["southwest airlines", "travel"],
  ["american airlines", "travel"],
  ["delta airlines", "travel"],
  ["united airlines", "travel"],
  ["jetblue airways", "travel"],
  ["alaska airlines", "travel"],
  ["spirit airlines", "travel"],
  ["frontier airlines", "travel"],
  ["hawaiian airlines", "travel"],
  ["rental car", "travel"],
  ["enterprise rent", "travel"],
  ["hertz rent", "travel"],
  ["avis rent", "travel"],
  ["national car", "travel"],
  ["budget rent", "travel"],
  ["dollar rent", "travel"],
  ["thrifty rent", "travel"],
  ["alamo rent", "travel"],
  ["sixt rent", "travel"],
  ["southwest.com", "travel"],
  ["united.com", "travel"],
  ["delta.com", "travel"],
  ["aa.com", "travel"],
  ["marriott", "travel"],
  ["hilton hotel", "travel"],
  ["hyatt hotel", "travel"],
  ["ihg hotel", "travel"],
  ["wyndham", "travel"],
  ["holiday inn", "travel"],
  ["best western", "travel"],
  ["la quinta", "travel"],
  ["red roof", "travel"],
  ["motel 6", "travel"],
  ["airport parking", "travel"],
  ["long term parking", "travel"],
  ["park 'n fly", "travel"],
  ["park n fly", "travel"],
  ["tsa pre", "travel"],
  ["global entry", "travel"],
  ["clear me", "travel"],

  // Grocery / food retail
  ["whole foods market", "grocery"],
  ["trader joe's", "grocery"],
  ["trader joes", "grocery"],
  ["stop & shop", "grocery"],
  ["stop and shop", "grocery"],
  ["food lion", "grocery"],
  ["giant food", "grocery"],
  ["giant eagle", "grocery"],
  ["harris teeter", "grocery"],
  ["food 4 less", "grocery"],
  ["smart & final", "grocery"],
  ["smart and final", "grocery"],
  ["99 ranch", "grocery"],
  ["hmart", "grocery"],
  ["mitsuwa", "grocery"],
  ["nijiya", "grocery"],
  ["shoprite", "grocery"],
  ["acme market", "grocery"],
  ["king soopers", "grocery"],
  ["fry's food", "grocery"],
  ["smith's food", "grocery"],
  ["city market", "grocery"],
  ["dillons", "grocery"],
  ["baker's", "grocery"],
  ["gerbes", "grocery"],
  ["pay less", "grocery"],
  ["roundy's", "grocery"],
  ["pick 'n save", "grocery"],
  ["metro market", "grocery"],
  ["mariano's", "grocery"],
  ["pete's fresh", "grocery"],
  ["fairway market", "grocery"],
  ["morton williams", "grocery"],
  ["brookshire", "grocery"],
  ["randalls", "grocery"],
  ["tom thumb", "grocery"],
  ["united supermarket", "grocery"],
  ["market basket", "grocery"],
  ["price chopper", "grocery"],
  ["market 32", "grocery"],
  ["tops markets", "grocery"],
  ["weis markets", "grocery"],
  ["redner's", "grocery"],
  ["giant martin", "grocery"],
  ["food bazaar", "grocery"],
  ["compare foods", "grocery"],
  ["c town", "grocery"],
  ["key food", "grocery"],
  ["associated super", "grocery"],
  ["western beef", "grocery"],
  ["super fresh", "grocery"],
  ["supermarket", "grocery"],
  ["food mart", "grocery"],
  ["mini mart", "grocery"],
  ["convenience", "grocery"],
  ["petco", "grocery"],
  ["petsmart", "grocery"],
  ["pet smart", "grocery"],
  ["chewy.com", "grocery"],
  ["chewy com", "grocery"],

  // Dining
  ["olive garden", "dining"],
  ["red lobster", "dining"],
  ["outback steakhouse", "dining"],
  ["texas roadhouse", "dining"],
  ["longhorn steakhouse", "dining"],
  ["cracker barrel", "dining"],
  ["buffalo wild wings", "dining"],
  ["applebee's", "dining"],
  ["chili's grill", "dining"],
  ["chilis grill", "dining"],
  ["tgi fridays", "dining"],
  ["red robin", "dining"],
  ["cheesecake factory", "dining"],
  ["p f chang", "dining"],
  ["pf chang", "dining"],
  ["yard house", "dining"],
  ["bjs restaurant", "dining"],
  ["bjs brewhouse", "dining"],
  ["the habit", "dining"],
  ["five guys", "dining"],
  ["shake shack", "dining"],
  ["in-n-out", "dining"],
  ["in n out", "dining"],
  ["whataburger", "dining"],
  ["culver's", "dining"],
  ["zaxby's", "dining"],
  ["bojangles", "dining"],
  ["raising cane", "dining"],
  ["wingstop", "dining"],
  ["domino's pizza", "dining"],
  ["papa john", "dining"],
  ["little caesars", "dining"],
  ["pizza hut", "dining"],
  ["papa murphy", "dining"],
  ["blaze pizza", "dining"],
  ["mod pizza", "dining"],
  ["qdoba", "dining"],
  ["moe's southwest", "dining"],
  ["baja fresh", "dining"],
  ["del taco", "dining"],
  ["jack in the box", "dining"],
  ["carl's jr", "dining"],
  ["hardee's", "dining"],
  ["white castle", "dining"],
  ["checkers", "dining"],
  ["rally's", "dining"],
  ["cook out", "dining"],
  ["cookout", "dining"],
  ["tim hortons", "dining"],
  ["dutch bros", "dining"],
  ["peet's coffee", "dining"],
  ["dutch bros coffee", "dining"],
  ["coffee bean", "dining"],
  ["philz coffee", "dining"],
  ["gregorys coffee", "dining"],
  ["smoothie king", "dining"],
  ["jamba juice", "dining"],
  ["tropical smoothie", "dining"],
  ["bob evans", "dining"],
  ["waffle house", "dining"],
  ["huddle house", "dining"],
  ["perkins", "dining"],
  ["village inn", "dining"],
  ["first watch", "dining"],
  ["another broken egg", "dining"],
  ["corner bakery", "dining"],
  ["panera bread", "dining"],
  ["einstein bros", "dining"],
  ["bruegger's", "dining"],
  ["dunkin donuts", "dining"],
  ["krispy kreme", "dining"],
  ["baskin robbins", "dining"],
  ["cold stone", "dining"],
  ["yogurtland", "dining"],
  ["menchie's", "dining"],
  ["sweetgreen", "dining"],
  ["cava grill", "dining"],
  ["noodles & company", "dining"],
  ["noodles and company", "dining"],
  ["panda express", "dining"],
  ["pick up stix", "dining"],
  ["pei wei", "dining"],
  ["benihana", "dining"],
  ["benihan", "dining"],
  ["hibachi", "dining"],
  ["buffet", "dining"],
  ["all you can eat", "dining"],
  ["uber eats", "dining"],
  ["doordash", "dining"],
  ["grubhub", "dining"],
  ["postmates", "dining"],
  ["seamless", "dining"],
  ["caviar", "dining"],
  ["toast tab", "dining"],
  ["toasttab", "dining"],
  ["clover pos", "dining"],
  ["square *", "dining"],
  ["sq *", "dining"],
  ["tst*", "dining"],
  ["tsp*", "dining"],

  // Gas / auto fuel
  ["quik trip", "gas"],
  ["quick trip", "gas"],
  ["racetrac", "gas"],
  ["race trac", "gas"],
  ["wawa", "gas"],
  ["sheetz", "gas"],
  ["kum & go", "gas"],
  ["kum and go", "gas"],
  ["casey's", "gas"],
  ["caseys general", "gas"],
  ["maverick", "gas"],
  ["maverik", "gas"],
  ["thorntons", "gas"],
  ["kwik trip", "gas"],
  ["holiday station", "gas"],
  ["getgo", "gas"],
  ["royal farms", "gas"],
  ["murphy usa", "gas"],
  ["murphy express", "gas"],
  ["valero", "gas"],
  ["citgo", "gas"],
  ["sunoco", "gas"],
  ["texaco", "gas"],
  ["marathon pet", "gas"],
  ["phillips 66", "gas"],
  ["conoco", "gas"],
  ["arco", "gas"],
  ["ampm", "gas"],
  ["76 gas", "gas"],
  ["sinclair", "gas"],
  ["flying j", "gas"],
  ["pilot flying", "gas"],
  ["loves travel", "gas"],
  ["ta travel", "gas"],
  ["petro stopping", "gas"],
  ["gas station", "gas"],
  ["fuel center", "gas"],
  ["fuel stop", "gas"],
  ["car wash", "gas"],

  // Transit / parking
  ["uber trip", "transit"],
  ["uber *trip", "transit"],
  ["lyft ride", "transit"],
  ["lyft *ride", "transit"],
  ["lyft *", "transit"],
  ["yellow cab", "transit"],
  ["taxi", "transit"],
  ["parking garage", "transit"],
  ["parkmobile", "transit"],
  ["parkwhiz", "transit"],
  ["spothero", "transit"],
  ["ez pass", "transit"],
  ["fastrak", "transit"],
  ["sunpass", "transit"],
  ["ipass illinois", "transit"],
  ["good to go", "transit"],
  ["metro north", "transit"],
  ["long island rail", "transit"],
  ["nj transit", "transit"],
  ["bart clipper", "transit"],
  ["clipper card", "transit"],
  ["ventra", "transit"],
  ["orca card", "transit"],
  ["omny", "transit"],
  ["mta new york", "transit"],
  ["cta chicago", "transit"],
  ["wmata", "transit"],
  ["septa", "transit"],
  ["marta atlanta", "transit"],
  ["vta santa", "transit"],
  ["caltrain", "transit"],
  ["metrolink", "transit"],
  ["amtrak", "transit"],
  ["greyhound", "transit"],
  ["megabus", "transit"],
  ["boltbus", "transit"],
  ["flixbus", "transit"],

  // Streaming / digital subs
  ["apple tv", "streaming"],
  ["apple music", "streaming"],
  ["youtube tv", "streaming"],
  ["youtube premium", "streaming"],
  ["youtube red", "streaming"],
  ["hbo max", "streaming"],
  ["max stream", "streaming"],
  ["paramount+", "streaming"],
  ["paramount plus", "streaming"],
  ["discovery+", "streaming"],
  ["discovery plus", "streaming"],
  ["showtime", "streaming"],
  ["starz", "streaming"],
  ["epix", "streaming"],
  ["sling tv", "streaming"],
  ["fubo tv", "streaming"],
  ["philo tv", "streaming"],
  ["directv stream", "streaming"],
  ["directv now", "streaming"],
  ["sling television", "streaming"],
  ["audible", "streaming"],
  ["kindle unlimited", "streaming"],
  ["kindle svcs", "streaming"],
  ["sirius xm", "streaming"],
  ["siriusxm", "streaming"],
  ["pandora", "streaming"],
  ["iheart", "streaming"],
  ["nytimes", "streaming"],
  ["new york times", "streaming"],
  ["washington post", "streaming"],
  ["wsj subscription", "streaming"],
  ["wall street journal", "streaming"],
  ["medium.com", "streaming"],
  ["substack", "streaming"],
  ["patreon", "streaming"],
  ["onlyfans", "streaming"],
  ["dropbox", "streaming"],
  ["icloud", "streaming"],
  ["google one", "streaming"],
  ["google storage", "streaming"],
  ["microsoft 365", "streaming"],
  ["office 365", "streaming"],
  ["adobe creative", "streaming"],
  ["adobe inc", "streaming"],
  ["canva", "streaming"],
  ["notion labs", "streaming"],
  ["1password", "streaming"],
  ["lastpass", "streaming"],
  ["dashlane", "streaming"],
  ["norton lifelock", "streaming"],
  ["mcafee", "streaming"],

  // Drugstore / health retail
  ["cvs pharmacy", "drugstore"],
  ["cvs caremark", "drugstore"],
  ["walgreens", "drugstore"],
  ["rite aid", "drugstore"],
  ["duane reade", "drugstore"],
  ["navarro discount", "drugstore"],
  ["good neighbor", "drugstore"],
  ["health mart", "drugstore"],
  ["express scripts", "drugstore"],
  ["optumrx", "drugstore"],
  ["cigna pharmacy", "drugstore"],
  ["minute clinic", "drugstore"],

  // Entertainment / fitness / hobbies
  ["planet fitness", "entertainment"],
  ["la fitness", "entertainment"],
  ["24 hour fitness", "entertainment"],
  ["anytime fitness", "entertainment"],
  ["gold's gym", "entertainment"],
  ["equinox", "entertainment"],
  ["lifetime fitness", "entertainment"],
  ["ymca", "entertainment"],
  ["orangetheory", "entertainment"],
  ["soulcycle", "entertainment"],
  ["pure barre", "entertainment"],
  ["crossfit", "entertainment"],
  ["golf course", "entertainment"],
  ["topgolf", "entertainment"],
  ["dave & buster", "entertainment"],
  ["dave and buster", "entertainment"],
  ["main event", "entertainment"],
  ["round1", "entertainment"],
  ["sky zone", "entertainment"],
  ["urban air", "entertainment"],
  ["legoland", "entertainment"],
  ["six flags", "entertainment"],
  ["cedar point", "entertainment"],
  ["universal studio", "entertainment"],
  ["disney world", "entertainment"],
  ["disneyland", "entertainment"],
  ["seaworld", "entertainment"],
  ["busch garden", "entertainment"],
  ["bookstore", "entertainment"],
  ["barnes noble", "entertainment"],
  ["books a million", "entertainment"],
  ["half price books", "entertainment"],

  // Wholesale
  ["costco wholesale", "wholesale"],
  ["sam's club", "wholesale"],
  ["sams club", "wholesale"],
  ["bj's wholesale", "wholesale"],
  ["bjs wholesale", "wholesale"],

  // Online shopping / retail / tech
  ["amazon.com", "online_shopping"],
  ["amazon mktplace", "online_shopping"],
  ["amazon retail", "online_shopping"],
  ["amazon web", "online_shopping"],
  ["amzn mktp", "online_shopping"],
  ["amzn.com", "online_shopping"],
  ["ebay inc", "online_shopping"],
  ["ebay *", "online_shopping"],
  ["etsy.com", "online_shopping"],
  ["shopify", "online_shopping"],
  ["wayfair", "online_shopping"],
  ["overstock", "online_shopping"],
  ["wish.com", "online_shopping"],
  ["shein", "online_shopping"],
  ["temu", "online_shopping"],
  ["mercari", "online_shopping"],
  ["poshmark", "online_shopping"],
  ["depop", "online_shopping"],
  ["stockx", "online_shopping"],
  ["goat com", "online_shopping"],
  ["nike.com", "online_shopping"],
  ["adidas", "online_shopping"],
  ["under armour", "online_shopping"],
  ["lululemon", "online_shopping"],
  ["uniqlo", "online_shopping"],
  ["zara", "online_shopping"],
  ["h&m", "online_shopping"],
  ["hm ", "online_shopping"],
  ["old navy", "online_shopping"],
  ["gap ", "online_shopping"],
  ["banana republic", "online_shopping"],
  ["jcrew", "online_shopping"],
  ["j.crew", "online_shopping"],
  ["madewell", "online_shopping"],
  ["urban outfitters", "online_shopping"],
  ["anthropologie", "online_shopping"],
  ["free people", "online_shopping"],
  ["rei ", "online_shopping"],
  ["dick's sporting", "online_shopping"],
  ["dicks sporting", "online_shopping"],
  ["academy sports", "online_shopping"],
  ["bass pro", "online_shopping"],
  ["cabela's", "online_shopping"],
  ["home depot", "online_shopping"],
  ["homedepot", "online_shopping"],
  ["lowe's", "online_shopping"],
  ["lowes ", "online_shopping"],
  ["menards", "online_shopping"],
  ["ace hardware", "online_shopping"],
  ["harbor freight", "online_shopping"],
  ["autozone", "online_shopping"],
  ["advance auto", "online_shopping"],
  ["o'reilly auto", "online_shopping"],
  ["oreilly auto", "online_shopping"],
  ["napa auto", "online_shopping"],
  ["best buy", "online_shopping"],
  ["bestbuy", "online_shopping"],
  ["micro center", "online_shopping"],
  ["fry's electron", "online_shopping"],
  ["b&h photo", "online_shopping"],
  ["bh photo", "online_shopping"],
  ["newegg", "online_shopping"],
  ["apple store", "online_shopping"],
  ["apple.com", "online_shopping"],
  ["apple.com/bill", "online_shopping"],
  ["google *", "online_shopping"],
  ["google play", "online_shopping"],
  ["microsoft*store", "online_shopping"],
  ["microsoft store", "online_shopping"],
  ["xbox", "online_shopping"],
  ["playstation", "online_shopping"],
  ["nintendo", "online_shopping"],
  ["steamgames", "online_shopping"],
  ["steampowered", "online_shopping"],
  ["epic games", "online_shopping"],
  ["roblox", "online_shopping"],
  ["target.com", "online_shopping"],
  ["walmart.com", "online_shopping"],
  ["walmart super", "online_shopping"],
  ["kohls", "online_shopping"],
  ["kohl's", "online_shopping"],
  ["macy's", "online_shopping"],
  ["macys", "online_shopping"],
  ["nordstrom", "online_shopping"],
  ["neiman marcus", "online_shopping"],
  ["saks fifth", "online_shopping"],
  ["bloomingdale", "online_shopping"],
  ["dillard's", "online_shopping"],
  ["belk ", "online_shopping"],
  ["jcpenney", "online_shopping"],
  ["ross dress", "online_shopping"],
  ["tj maxx", "online_shopping"],
  ["marshalls", "online_shopping"],
  ["homegoods", "online_shopping"],
  ["burlington", "online_shopping"],
  ["big lots", "online_shopping"],
  ["dollar general", "online_shopping"],
  ["dollar tree", "online_shopping"],
  ["family dollar", "online_shopping"],
  ["five below", "online_shopping"],
  ["paypal *", "online_shopping"],
  ["stripe *", "online_shopping"],

  // Utilities / telecom / insurance (recurring bills)
  ["comcast", "utilities"],
  ["xfinity", "utilities"],
  ["spectrum", "utilities"],
  ["charter comm", "utilities"],
  ["cox communications", "utilities"],
  ["verizon wireless", "utilities"],
  ["verizon bill", "utilities"],
  ["at&t mobility", "utilities"],
  ["at&t payment", "utilities"],
  ["att mobility", "utilities"],
  ["att payment", "utilities"],
  ["t-mobile", "utilities"],
  ["tmobile", "utilities"],
  ["sprint ", "utilities"],
  ["cricket wireless", "utilities"],
  ["metro by t", "utilities"],
  ["mint mobile", "utilities"],
  ["visible wireless", "utilities"],
  ["google fi", "utilities"],
  ["duke energy", "utilities"],
  ["dominion energy", "utilities"],
  ["pacific gas", "utilities"],
  ["pge ", "utilities"],
  ["southern california edison", "utilities"],
  ["con edison", "utilities"],
  ["national grid", "utilities"],
  ["xcel energy", "utilities"],
  ["entergy", "utilities"],
  ["fpl florida", "utilities"],
  ["fp&l", "utilities"],
  ["geico", "utilities"],
  ["state farm", "utilities"],
  ["progressive ins", "utilities"],
  ["allstate", "utilities"],
  ["liberty mutual", "utilities"],
  ["usaa ins", "utilities"],
  ["farmers insur", "utilities"],
  ["travelers ins", "utilities"],
  ["nationwide ins", "utilities"],
  ["american family", "utilities"],
  ["erie insurance", "utilities"],
];

/** Longest phrase first to prefer specific matches */
const SNIPPETS = SNIPPETS_RAW.sort((a, b) => b[0].length - a[0].length);

/**
 * @param {string} lower Already lowercased merchant text.
 * @returns {import("./categories.js").CategoryId | null}
 */
export function matchMerchantSnippet(lower) {
  for (const [phrase, cat] of SNIPPETS) {
    if (lower.includes(phrase)) return cat;
  }
  return null;
}
